# Generated by Django 4.1.13 on 2024-06-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_bid_auction_bid_item_delete_auction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
