# Generated by Django 4.1.13 on 2024-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='primary',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
