# Generated by Django 4.1.13 on 2024-06-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
