# Generated by Django 4.1.13 on 2024-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banner_item',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
