# Generated by Django 4.1.13 on 2024-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_item_banner_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='banner_item',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_item',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
