# Generated by Django 4.1.13 on 2024-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_item_banner_item_alter_item_featured_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banner_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='featured_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
