# Generated by Django 4.1.13 on 2024-07-04 08:05

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_item_banner_fee_item_featured_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=djongo.models.fields.ArrayReferenceField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
