# Generated by Django 4.1.13 on 2024-07-04 13:03

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_alter_featurebanner_item_alter_featurebanner_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurebanner',
            name='owner',
        ),
        migrations.AddField(
            model_name='featurebanner',
            name='user',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_banners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='featurebanner',
            name='item',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_banners', to='store.item'),
        ),
        migrations.AlterField(
            model_name='featurebanner',
            name='order',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_banners', to='store.order'),
        ),
    ]
