# Generated by Django 4.1.13 on 2024-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_order_for_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_for',
            field=models.CharField(blank=True, choices=[('Item', 'Item'), ('Auction', 'Auction'), ('FeatureBanner', 'Feature/Banner')], default='Item', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True),
        ),
    ]
