from django.urls import path, include
from . import views
from .views import CustomLoginView, custom_password_change, custom_password_change_done

urlpatterns = [
    path('', views.home, name='home'),
    path("accounts/login/", CustomLoginView.as_view(), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/signup/', views.signup, name='signup'),
    path("password_change/", custom_password_change, name="password_change"),
    path("password_change/done/", custom_password_change_done, name="password_change_done"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create-item/', views.create_item, name='create_item'),
    path('edit-item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('update-cart-item/', views.update_cart_item, name='update_cart_item'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('soft_delete_item/<int:item_id>/', views.soft_delete_item, name='soft_delete_item'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('profile/edit_shipping_address/<int:address_id>/', views.edit_shipping_address, name='edit_shipping_address'),
    path('profile/add_shipping_address/', views.add_shipping_address, name='add_shipping_address'),
    path('profile/delete_shipping_address/<int:address_id>/', views.delete_shipping_address, name='delete_shipping_address'),
    path('place_order/', views.place_order, name='place_order'),
    path('thankyou/<int:order_id>/', views.thankyou, name='thankyou'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('select-shipping/', views.select_shipping, name='select-shipping'),
    path('orders/', views.order_history_view, name='order_history'),
    path('orders-users/', views.order_history_users, name='order_history_users'),
    path('export-orders-pdf/', views.export_orders_pdf, name='export_orders_pdf'),
    path('export_orders_excel/', views.export_orders_excel, name='export_orders_excel'),
    path('category/<int:category_id>/', views.category_items, name='category_items'),
    path('auctions/', views.auctions, name='auctions'),
    path('auction/<int:item_id>/', views.auction_details, name='auction-details'),
    path('auction/<int:item_id>/place-bid/', views.place_bid, name='place_bid'),
    path('place_auto_bid/<int:item_id>/', views.place_auto_bid, name='place_auto_bid'),
    path('auction/<int:item_id>/check-master-bidder/', views.check_master_bidder, name='check_master_bidder'),
    path('item-details/<int:item_id>/', views.item_details, name='item-details'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('error/', views.error, name='error'),
    path('userprofile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('<str:table_name>/', views.DynamicListView.as_view(), name='dynamic_list'),
    path('<str:table_name>/create/', views.DynamicCreateView.as_view(), name='dynamic_create'),
    path('<str:table_name>/update/<int:pk>/', views.DynamicUpdateView.as_view(), name='dynamic_update'),
    path('<str:table_name>/delete/<int:pk>/', views.DynamicDeleteView.as_view(), name='dynamic_delete'),
    path('itemimages/<int:item_id>/', views.manage_item_images, name='manage_item_images'),
    path('orderitems/<int:order_id>/', views.manage_order_items, name='manage_order_items'),
    path('categoryitems/<int:category_id>/', views.manage_category_items, name='manage_category_items'),
    path('bids/<int:item_id>/', views.manage_bids, name='manage_bids'),
]